project 'AttendBot.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AttendBot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "Pastel"
  pod 'DatePickerDialog'
  pod 'RealmSwift'
pod 'Charts'
pod 'SkyFloatingLabelTextField'


pod 'Instructions'
pod 'CalendarKit'
  # Pods for AttendBot

  target 'AttendBotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AttendBotUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
